/**
 * DailyDigest Component
 * 
 * AI-generated daily email summary using Shadcn Card
 */

import { useEffect, useState } from 'react'
import { BarChart3, Mail, RefreshCw } from 'lucide-react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { emailService } from '@/services/emailService'

export default function DailyDigest() {
  // const [digest, setDigest] = useState(null)
  // const [loading, setLoading] = useState(true)

  // Fetch digest on mount
  // useEffect(() => {
  //   fetchDigest()
  // }, [])

  // const fetchDigest = async () => {
  //   setLoading(true)
  //   try {
  //     const data = await emailService.getEmailDigest()
  //     setDigest(data)
  //   } catch (error) {
  //     console.error('Failed to fetch digest:', error)
  //   } finally {
  //     setLoading(false)
  //   }
  // }

  // if (loading) {
  //   return (
  //     <Card>
  //       <CardHeader>
  //         <Skeleton className="h-6 w-48" />
  //         <Skeleton className="h-4 w-32" />
  //       </CardHeader>
  //       <CardContent className="space-y-3">
  //         <Skeleton className="h-4 w-full" />
  //         <Skeleton className="h-4 w-3/4" />
  //         <Skeleton className="h-4 w-5/6" />
  //       </CardContent>
  //     </Card>
  //   )
  // }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <BarChart3 className="h-5 w-5" />
              Your Daily Email Digest
            </CardTitle>
            <CardDescription>Today, {/* new Date().toLocaleDateString() */}</CardDescription>
          </div>
          {/* <Button variant="ghost" size="icon" onClick={fetchDigest}>
            <RefreshCw className="h-4 w-4" />
          </Button> */}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Statistics */}
        {/* <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Mail className="h-4 w-4 text-muted-foreground" />
            <span className="text-sm">You received <strong>{digest?.totalEmails}</strong> emails today</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {Object.entries(digest?.categories || {}).map(([category, count]) => (
              <Badge key={category} variant="outline">
                {category}: {count}
              </Badge>
            ))}
          </div>
        </div> */}

        {/* <Separator /> */}

        {/* Top Priority */}
        {/* {digest?.topPriority?.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold mb-2">⭐ Top Priority:</h4>
            <ul className="space-y-1">
              {digest.topPriority.map((email, index) => (
                <li key={index} className="text-sm text-muted-foreground">
                  • {email.subject} - {email.from}
                </li>
              ))}
            </ul>
          </div>
        )} */}

        {/* AI Summary */}
        {/* {digest?.aiSummary && (
          <p className="text-sm text-muted-foreground italic">
            {digest.aiSummary}
          </p>
        )} */}
      </CardContent>
    </Card>
  )
}
 * 
 * Features:
 * 
 * 1. Summary Statistics:
 *    - Total emails received today
 *    - Count by category (Important, Social, etc.)
 *    - Number of unread emails
 *    - Emails with attachments
 * 
 * 2. AI-Generated Insights:
 *    - "You have 3 urgent emails"
 *    - "Most emails are from newsletters"
 *    - "5 emails require your response"
 *    - Generated by Gemini AI
 * 
 * 3. Top Priority List:
 *    - Show 3-5 most important emails
 *    - Brief subject line
 *    - Sender name
 *    - Why it's important (AI reasoning)
 * 
 * 4. Visual Elements:
 *    - Card/panel design
 *    - Icon for each stat
 *    - Progress bars (optional)
 *    - Color-coded categories
 * 
 * 5. Actions:
 *    - "View All Emails" button
 *    - "Refresh Digest" button
 *    - Click priority email to open
 * 
 * 6. Loading State:
 *    - Skeleton loader
 *    - "Generating digest..." message
 *    - Animated AI icon
 * 
 * 7. Empty State:
 *    - "No new emails today"
 *    - Friendly message
 *    - Illustration
 * 
 * Data Structure:
 * {
 *   date: "2024-12-02",
 *   totalEmails: 24,
 *   categories: {
 *     important: 5,
 *     social: 8,
 *     promotions: 11
 *   },
 *   unreadCount: 12,
 *   aiSummary: "You have several urgent emails...",
 *   topPriority: [
 *     {
 *       id: "email_1",
 *       subject: "Meeting invite",
 *       from: "boss@company.com",
 *       reason: "From your manager"
 *     }
 *   ]
 * }
 * 
 * API Call:
 * - GET /api/v1/emails/digest
 * - Returns AI-generated digest
 * - Cached for 1 hour
 * 
 * Props:
 * - None (fetches own data)
 * - Or: digest object (passed from parent)
 * 
 * States:
 * - digest: object | null
 * - loading: boolean
 * - error: string | null
 * 
 * Usage:
 * <DailyDigest />
 * 
 * // On dashboard:
 * <div className="mb-6">
 *   <DailyDigest />
 * </div>
 */

// Will import emailService.getEmailDigest()
// Will import Shadcn Card, Badge
// Will display AI-generated summary
// Will show statistics and top emails
